name: Deployment

on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string
      deploy-path:
        required: true
        type: string
    secrets:
      deploy-key:
        required: true
      deploy-user:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Create config
        run: |
          echo "url: https://${{ inputs.host }}" > _config.ext.yml
          echo 'baseurl: ""' >> _config.ext.yml
          cat _config.ext.yml

      - name: Build Jekyll site
        run: bundle exec jekyll build --config _config.yml,_config.ext.yml
        env:
          JEKYLL_ENV: production

      - uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.deploy-key }}

      - name: Deploy to ${{ inputs.host }}
        run: |
          rsync -rlvz --delete \
            --exclude=robots.txt \
            --exclude=google*.html \
            -e 'ssh -o StrictHostKeyChecking=no' \
            _site/ \
            ${{ secrets.deploy-user }}@${{ inputs.host }}:${{ inputs.deploy-path }}/
